### PR TITLE
Changes for lab

### PR DESCRIPTION
**Pull request by jemarbush1**
Here is where I'm at, but I had to make another repo because the issues I was having.

### CODE REVIEW

**Review by jschmersal-cscc — COMMENTED** [review]
Did you forget to add your `build.gradle` and `settings.gradle` files?  I'm not seeing any new files here, and only a change to the `<scope>` of a dependency, which is fine but not necessary.

**Comment by jemarbush1** [comment]
Yeah, that's where I made it to, back to square one. I'll work more on it this evening. 

Sent from Yahoo Mail on Android 
 
  On Sun, Nov 24, 2019 at 10:26 AM, jschmersal-cscc<notifications@github.com> wrote:   
@jschmersal-cscc commented on this pull request.

Did you forget to add your build.gradle and settings.gradle files? I'm not seeing any new files here, and only a change to the <scope> of a dependency, which is fine but not necessary.

**Comment by jemarbush1** [comment]
I got a little more done, but not sure on the rest.

**Comment by jschmersal-cscc** [comment]
Good start.  Your next step should be to compile an "executable fat jar", as the README.md indicates - 

```There are plenty of Gradle plugins available. You'll want to look through a few for your use cases (e.g. interacting with Docker). I'd suggest to use something that seems pretty straightforward and has good examples documented. For the "uber jar" (sometimes called a "fat jar") you can decide if you want to use a plugin or just use the built-in jar task, with appropriate configuration.```

As I said in the class, I would probably just augment the `jar` task, using the [configuration in the linked StackOverflow post](https://stackoverflow.com/questions/49278063/how-do-i-create-an-executable-fat-jar-with-gradle-with-implementation-dependenci).

**Comment by jemarbush1** [comment]
Okay, I believe that's where I got stuck, trying to complete the uber jar section. I'll review your feedback and try to get this done tonight. 

Sent from Yahoo Mail on Android 
 
  On Tue, Nov 26, 2019 at 12:29 PM, jschmersal-cscc<notifications@github.com> wrote:   
Good start. Your next step should be to compile an "executable fat jar", as the README.md indicates -

There are plenty of Gradle plugins available. You'll want to look through a few for your use cases (e.g. interacting with Docker). I'd suggest to use something that seems pretty straightforward and has good examples documented. For the "uber jar" (sometimes called a "fat jar") you can decide if you want to use a plugin or just use the built-in jar task, with appropriate configuration.

As I said in the class, I would probably just augment the jar task, using the configuration in the linked StackOverflow post.

**Comment by jemarbush1** [comment]
How many points will I get for not completing forward as of now?

Sent from Yahoo Mail on Android 
 
  On Tue, Nov 26, 2019 at 12:29 PM, jschmersal-cscc<notifications@github.com> wrote:   
Good start. Your next step should be to compile an "executable fat jar", as the README.md indicates -

There are plenty of Gradle plugins available. You'll want to look through a few for your use cases (e.g. interacting with Docker). I'd suggest to use something that seems pretty straightforward and has good examples documented. For the "uber jar" (sometimes called a "fat jar") you can decide if you want to use a plugin or just use the built-in jar task, with appropriate configuration.

As I said in the class, I would probably just augment the jar task, using the configuration in the linked StackOverflow post.

**Comment by jschmersal-cscc** [comment]
With having done two parts (moving the integration test) you've completed two of the five components.  They're not all equally weighted but that would give you 20/64 for the lab.  Given your current Blackboard score of 334 that would mean you're 6 points shy of the 360 to get a "P".  It seems like if you were to improve some of your quiz scores you could submit as-is and concentrate on those.    Your call.  I'll grade whatever is submitted.

**Comment by jemarbush1** [comment]
Okay, thanks. I'll rework some of the quizzes and may move more on the lab. I'll keep you posted with a final answer by 4PM today. 

Sent from Yahoo Mail on Android 
 
  On Wed, Nov 27, 2019 at 12:22 PM, jschmersal-cscc<notifications@github.com> wrote:   
With having done two parts (moving the integration test) you've completed two of the five components. They're not all equally weighted but that would give you 20/64 for the lab. Given your current Blackboard score of 334 that would mean you're 6 points shy of the 360 to get a "P". It seems like if you were to improve some of your quiz scores you could submit as-is and concentrate on those. Your call. I'll grade whatever is submitted.

**Comment by jemarbush1** [comment]
I got my quizzes up for the missing 6 points, I'm now at 340. I'll submit the build tools as is and take the 20. Which should put me at the mark of 360. Submitting work now.

Sent from Yahoo Mail on Android 
 
  On Wed, Nov 27, 2019 at 12:31 PM, Jemar Bush<jemarbush@yahoo.com> wrote:   Okay, thanks. I'll rework some of the quizzes and may move more on the lab. I'll keep you posted with a final answer by 4PM today. 

Sent from Yahoo Mail on Android 
 
  On Wed, Nov 27, 2019 at 12:22 PM, jschmersal-cscc<notifications@github.com> wrote:   
With having done two parts (moving the integration test) you've completed two of the five components. They're not all equally weighted but that would give you 20/64 for the lab. Given your current Blackboard score of 334 that would mean you're 6 points shy of the 360 to get a "P". It seems like if you were to improve some of your quiz scores you could submit as-is and concentrate on those. Your call. I'll grade whatever is submitted.

**Comment by jschmersal-cscc** [comment]
Thanks, Jemar.  I have sent an email to CSCC asking to change your grade to a “P” for this course.

Thanks,
Jeremy

**Comment by jemarbush1** [comment]
Thank you!

Sent from Yahoo Mail on Android 
 
  On Wed, Nov 27, 2019 at 9:20 PM, jschmersal-cscc<notifications@github.com> wrote:   Thanks, Jemar. I have sent an email to CSCC asking to change your grade to a “P” for this course.

Thanks,
Jeremy

**Pull request merged**
